#!/usr/bin/bash

# script to call dmenu and run scripts

dparam="-nb #08020f -nf #fea63c -sb #fea63c -sf #08020f -fn NotoMonoRegular:bold:pixelsize=14"

bind="/home/weirs/bin"
#locald="/home/weirs/.local/bin"

[[ -z "$1" ]] && dirc="$bind" || dirc="$1"

run="$(find $bind -type f -executable \
	| sed "s|/home/weirs/bin/||" | sort \
	| dmenu -i -l 5 $dparam -p "Scripts" )" || exit #removes the exit error

#[[ -z $run ]] && exit 0  # removes the error code
#bash "$bind/$run"
eval "$bind/$run"
